awesome-academy/hotel-booking

- app/Http/Controllers/Admin/LocationController.php
- app/Http/Requests/Admin/LocationRequest.php
- app/Models/Location.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Location/LocationRepository.php
- app/Repositories/Province/ProvinceRepository.php
- app/Repositories/Room/RoomRepository.php
- app/Repositories/RoomDetail/RoomDetailRepository.php
- resources/views/admin/layouts/aside.blade.php
- resources/views/admin/locations/create.blade.php
- resources/views/admin/locations/edit.blade.php
- resources/views/admin/locations/index.blade.php
- routes/admin.php
https://edu-redmine.sun-asterisk.vn/issues/12260
> Location Manage

- app/Http/Controllers/Admin/PropertyController.php
- app/Models/Comment.php
- app/Models/Invoice.php
- app/Models/Language.php
- app/Models/Property.php
- app/Models/Role.php
- resources/lang/vi/messages.php
- resources/views/admin/layouts/aside.blade.php
- resources/views/admin/properties/index.blade.php
- resources/views/admin/properties/translate.blade.php
https://edu-redmine.sun-asterisk.vn/issues/12261
> Properties Manage

- app/Http/Controllers/Client/HomeController.php
- app/Http/Requests/Client/SearchHomeRequest.php
- app/Providers/AppServiceProvider.php
- app/Repositories/EloquentRepository.php
- app/Repositories/Room/RoomRepository.php
- config/upload.php
- resources/lang/en/messages.php
- resources/lang/vi/messages.php
- resources/views/admin/rooms/edit.blade.php
- resources/views/client/index.blade.php
- resources/views/client/layouts/header.blade.php
- resources/views/client/layouts/slider.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/12263
> Client Homepage

- app/Http/Controllers/Client/RoomController.php
- app/Providers/AppServiceProvider.php
- resources/views/client/layouts/header.blade.php
- resources/views/client/layouts/page-breadcumb.blade.php
- resources/views/client/layouts/sidebar_rooms.blade.php
- resources/views/client/layouts/slider.blade.php
- resources/views/client/rooms/location.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/12264
> List Room Client

- app/Http/Controllers/Client/HomeController.php
- app/Http/Controllers/Client/RoomController.php
- app/Repositories/Room/RoomRepository.php
- config/pagination.php
- resources/views/admin/layouts/script.blade.php
- resources/views/admin/properties/index.blade.php
- resources/views/admin/rooms/create.blade.php
- resources/views/admin/rooms/edit.blade.php
- resources/views/admin/rooms/index.blade.php
- resources/views/admin/rooms/translate.blade.php
- resources/views/client/layouts/header.blade.php
- resources/views/client/layouts/master.blade.php
- resources/views/client/layouts/sidebar_rooms.blade.php
- resources/views/client/layouts/slider.blade.php
- resources/views/client/rooms/detail.blade.php
- resources/views/client/rooms/index.blade.php
https://edu-redmine.sun-asterisk.vn/issues/12266
> Filter Room

- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Controllers/Admin/LanguageController.php
- app/Http/Controllers/Admin/PostController.php
- app/Http/Requests/Admin/StorePost.php
- app/Http/Requests/Admin/UpdatePost.php
- app/Models/Post.php
- app/Repositories/EloquentRepository.php
- app/Repositories/Post/PostRepository.php
- bower.json
- database/migrations/2019_05_23_040522_add_image_to_posts_table.php
- resources/views/admin/posts/post.blade.php
- routes/admin.php
https://edu-redmine.sun-asterisk.vn/issues/12259
> post-manage

- app/Http/Controllers/Admin/PostController.php
- app/Http/Controllers/Client/PostController.php
- app/Repositories/EloquentRepository.php
- config/post.php
- resources/views/client/blog/blog.blade.php
- resources/views/client/blog/blog_category.blade.php
- resources/views/client/layouts/header.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/12269
> list&category post

- app/Http/Controllers/Admin/WebSettingController.php
- app/Http/Requests/Admin/WebSettingRequest.php
- app/Repositories/WebSetting/WebSettingRepository.php
- composer.lock
- config/upload.php
- resources/lang/vi/messages.php
- resources/views/admin/layouts/aside.blade.php
- resources/views/admin/webSetting/index.blade.php
- routes/admin.php
https://edu-redmine.sun-asterisk.vn/issues/12262
> Websetting

- app/Http/Controllers/Client/PostController.php
- config/contact.php
- resources/views/client/blog/blogDetail.blade.php
- resources/views/client/blog/blog_category.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/12271
> blogDetail

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Requests/ForgetPasswordRequest.php
- app/Http/Requests/ResetPasswordRequest.php
- resources/lang/vi/messages.php
- resources/views/auth/forget-password.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/reset-password-form.blade.php
- resources/views/mails/reset-password.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/12900
> Forget Password

- app/Http/Controllers/Admin/RoomController.php
- app/Http/Requests/Admin/StoreRoomRequest.php
- app/Http/Requests/Admin/UpdateRoomRequest.php
- app/Repositories/Room/RoomRepository.php
- resources/lang/vi/messages.php
- resources/views/admin/rooms/create.blade.php
- resources/views/admin/rooms/edit.blade.php
- routes/admin.php
https://edu-redmine.sun-asterisk.vn/issues/12920
> fix manage room number

- resources/views/client/rooms/detail.blade.php
https://edu-redmine.sun-asterisk.vn/issues/12944
> fix comment room detail

- app/Http/Controllers/Admin/CategoryController.php
- app/Http/Controllers/Admin/CommentController.php
- app/Http/Controllers/Admin/ContactController.php
- app/Http/Controllers/Admin/LanguageController.php
- app/Http/Controllers/Admin/PostController.php
- app/Http/Requests/Admin/StoreLanguage.php
- app/Http/Requests/Admin/UpdateLanguage.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Comment/CommentRepository.php
- resources/views/admin/comment/commentpost.blade.php
- resources/views/admin/comment/commentroom.blade.php
- resources/views/admin/languages/language.blade.php
- resources/views/admin/layouts/aside.blade.php
- resources/views/admin/layouts/header.blade.php
- routes/admin.php
https://edu-redmine.sun-asterisk.vn/issues/12951
> comment-manage

- app/Models/Category.php
- resources/views/client/layouts/header.blade.php
https://edu-redmine.sun-asterisk.vn/issues/13085
> User relationshop in header client

- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Client/PostController.php
- app/Providers/AppServiceProvider.php
- resources/views/client/blog/blogDetail.blade.php
- resources/views/client/layouts/sidebar_posts.blade.php
https://edu-redmine.sun-asterisk.vn/issues/13230
> Fix Language Bug

- app/Http/Controllers/Client/PostController.php
- app/Models/Room.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Room/RoomRepository.php
- resources/views/client/blog/blog.blade.php
- resources/views/client/layouts/sidebar_rooms.blade.php
https://edu-redmine.sun-asterisk.vn/issues/13467
> Make Filter Room By Properties

- app/Http/Controllers/Client/BookingController.php
- app/Repositories/Room/RoomRepository.php
- resources/lang/en/messages.php
- resources/lang/vi/messages.php
- resources/views/client/rooms/detail.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/13471
> Add booking room into room detail

- app/Console/Commands/UpdateSalePrice.php
- app/Console/Kernel.php
- app/Http/Controllers/Admin/RoomController.php
- app/Http/Requests/Admin/UpdateRoomRequest.php
- app/Repositories/EloquentRepository.php
- resources/views/admin/rooms/create.blade.php
- resources/views/admin/rooms/edit.blade.php
- resources/views/admin/rooms/index.blade.php
https://edu-redmine.sun-asterisk.vn/issues/13478
> Auto Update Sale Price

- app/Events/CommentNotification.php
- app/Http/Controllers/Client/RoomController.php
- app/Models/Comment.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Room/RoomRepository.php
- composer.json
- composer.lock
- config/comment.php
- resources/views/admin/layouts/header.blade.php
- resources/views/admin/layouts/script.blade.php
- routes/channels.php
https://edu-redmine.sun-asterisk.vn/issues/13552
> Realtime Notification

- app/Events/Admin/Chat.php
- app/Events/Admin/ShowNewChat.php
- app/Http/Controllers/Admin/ChatController.php
- app/Http/Controllers/Client/ChatController.php
- app/Providers/AppServiceProvider.php
- app/helper.php
- composer.json
- composer.lock
- resources/lang/en/messages.php
- resources/lang/vi/messages.php
- resources/views/admin/chat/index.blade.php
- resources/views/client/layouts/chat.blade.php
- routes/admin.php
- routes/channels.php
https://edu-redmine.sun-asterisk.vn/issues/13692
> Chat With Admin #2

- app/Events/Admin/ShowNewChat.php
- app/Events/Admin/UpdateStatus.php
- app/Events/ShowUnread.php
- app/Http/Controllers/Admin/ChatController.php
- app/Http/Controllers/Client/ChatController.php
- app/Http/Controllers/Client/HomeController.php
- config/chat.php
- resources/lang/en/messages.php
- resources/lang/vi/messages.php
- resources/views/admin/chat/index.blade.php
- resources/views/admin/layouts/aside.blade.php
- resources/views/client/layouts/chat.blade.php
- routes/admin.php
https://edu-redmine.sun-asterisk.vn/issues/13789
> Chat With Admin #3

- app/Http/Controllers/Client/UserController.php
- app/Providers/AppServiceProvider.php
- app/Repositories/Invoice/InvoiceRepository.php
- resources/views/client/users/profile.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/13898
> Edit Invoice Client

- app/Http/Controllers/Auth/SocialAuthController.php
- app/Http/Requests/Client/SearchHomeRequest.php
- app/Models/SocialAccount.php
- app/Services/SocialAccountService.php
- composer.json
- composer.lock
- config/app.php
- config/services.php
- database/migrations/2019_06_24_145239_create_social_accounts_table.php
- resources/lang/en/messages.php
- resources/lang/vi/messages.php
- resources/views/auth/login.blade.php
- resources/views/client/booking/index.blade.php
- resources/views/client/layouts/master.blade.php
- resources/views/client/rooms/index.blade.php
- resources/views/client/rooms/location.blade.php
- routes/web.php
https://edu-redmine.sun-asterisk.vn/issues/13972
> Social Login

- app/Events/CommentEvent.php
- app/Http/Controllers/Client/PostController.php
- app/Http/Requests/Client/UpdateComment.php
- app/Models/Comment.php
- app/Repositories/EloquentRepository.php
- database/migrations/2019_06_26_023508_add_cookie_name_to_comments.php
- resources/js/app.js
- resources/js/components/CommentVue.vue
- resources/views/client/blog/blogDetail.blade.php
- resources/views/client/layouts/master.blade.php
- routes/web.php
> comment-realtime
